In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_style('darkgrid')

In [2]:
df = pd.read_csv("./data/IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.sample(5)

                                                  review sentiment
36929  Loretta Castorini (Cher)is a woman in her late...  positive
21741  Some films are just plain silly beyond explana...  negative
45486  Plague replaces femme fatale in this highly su...  positive
44163  I went to a screening of this movie and while ...  negative
25607  <br /><br />**********SPOILER ALERT***********...  negative

In [5]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

In [6]:
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn'

In [7]:
train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)

NameError: name 'train_test_split' is not defined

In [8]:
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

NameError: name 'train' is not defined

In [9]:
train_y.value_counts()

NameError: name 'train_y' is not defined

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

ModuleNotFoundError: No module named 'sklearn'

In [11]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

NameError: name 'TfidfVectorizer' is not defined

In [12]:
train_x.shape

NameError: name 'train_x' is not defined

In [13]:
train_x_vector.shape

NameError: name 'train_x_vector' is not defined

In [14]:
type(train_x_vector)

NameError: name 'train_x_vector' is not defined

In [15]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]

NameError: name 'train_x_vector' is not defined

In [16]:
primera_resenia

NameError: name 'primera_resenia' is not defined

In [17]:
train_x.iloc[0]

NameError: name 'train_x' is not defined

In [18]:
primera_resenia[primera_resenia != 0]

NameError: name 'primera_resenia' is not defined

In [19]:
train_x.iloc[0]

NameError: name 'train_x' is not defined

In [20]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

ModuleNotFoundError: No module named 'sklearn'

In [21]:
print(svc.predict(tfidf.transform(['A good movie'])))
print(svc.predict(tfidf.transform(['An excellent movie'])))
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

NameError: name 'svc' is not defined

In [22]:
print(svc.score(test_x_vector, test_y))

NameError: name 'svc' is not defined

In [23]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

ModuleNotFoundError: No module named 'sklearn'

In [24]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

ModuleNotFoundError: No module named 'sklearn'

In [25]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

ModuleNotFoundError: No module named 'sklearn'